---------------------------------------------------------------------------------------------------
--                                       DATABASE CREATION                                              --
---------------------------------------------------------------------------------------------------

-- CREATE DATABASE --
CREATE DATABASE `ryzom_api` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

---------------------------------------------------------------------------------------------------
--                                         GUILDS LIST TABLE                                                --
---------------------------------------------------------------------------------------------------

-- CREATE GUILDS LIST TABLE --
CREATE TABLE `guilds_list` (
`gid` INT NOT NULL ,
`shardid` VARCHAR( 3 ) NOT NULL ,
`name` VARCHAR(120) NOT NULL ,
`race` VARCHAR(10) NOT NULL ,
`icon` VARCHAR(50) NOT NULL ,
`creation_date` DOUBLE NOT NULL ,
`description` TEXT NOT NULL ,
`deleted` BOOLEAN NOT NULL ,
`deletion_date` DOUBLE NOT NULL ,
UNIQUE (
`gid`
)
);

---------------------------------------------------------------------------------------------------
--                                      CHARACTER TABLES                                                   --
---------------------------------------------------------------------------------------------------

-- CREATE SINGLE CHARACTER TABLE --
CREATE TABLE `character_history` (
`cid` INT NOT NULL ,
`uid` INT NOT NULL ,
`slot` INT NOT NULL ,
`shard` VARCHAR(10) NOT NULL ,
`race` VARCHAR(10) NOT NULL ,
`gender` VARCHAR(1) NOT NULL ,
`apikey` VARCHAR( 30 ) NOT NULL ,
`date_first` DOUBLE NOT NULL ,
`date_last` DOUBLE NOT NULL ,
UNIQUE (
`cid`
)
);

-- CREATE SINGLE CHARACTER INFO TABLE --
CREATE TABLE `character_info_history` (
`cid` INT NOT NULL ,
`name` VARCHAR(16) NOT NULL ,
`titleid` VARCHAR(75) NOT NULL ,
`played_time` DOUBLE NOT NULL ,
`money` DOUBLE NOT NULL ,
`cult` VARCHAR(10) NOT NULL ,
`civ` VARCHAR(10) NOT NULL ,
`building` VARCHAR(15) NOT NULL ,
`guild_gid` VARCHAR(15) NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER PHYS CARACS TABLE --
CREATE TABLE `character_phys_caracs_history` (
`cid` INT NOT NULL ,
`constitution` INT NOT NULL ,
`metabolism` INT NOT NULL ,
`intelligence` INT NOT NULL ,
`wisdom` INT NOT NULL ,
`strength` INT NOT NULL ,
`wellbalanced` INT NOT NULL ,
`dexterity` INT NOT NULL ,
`will` INT NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER PHYS SCORES TABLE --
CREATE TABLE `character_phys_scores_history` (
`cid` INT NOT NULL ,
`hitpoints` INT NOT NULL ,
`hitpoints_max` INT NOT NULL ,
`stamina` INT NOT NULL ,
`stamina_max` INT NOT NULL ,
`sap` INT NOT NULL ,
`sap_max` INT NOT NULL ,
`focus` INT NOT NULL ,
`focus_max` INT NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER EQUIPHANDS TABLE --
CREATE TABLE `character_equiphands_history` (
`cid` INT NOT NULL ,
`equipments_feet` VARCHAR(75) NOT NULL , -- Note: sheet#c#q (e.g. ictahb_3.sitem#0#250)
`equipments_hands` VARCHAR(75) NOT NULL ,
`equipments_legs` VARCHAR(75) NOT NULL ,
`equipments_arms` VARCHAR(75) NOT NULL ,
`equipments_chest` VARCHAR(75) NOT NULL ,
`equipments_ankle_l` VARCHAR(75) NOT NULL ,
`equipments_ankle_r` VARCHAR(75) NOT NULL ,
`equipments_wrist_l` VARCHAR(75) NOT NULL ,
`equipments_wrist_r` VARCHAR(75) NOT NULL ,
`equipments_head_dress` VARCHAR(75) NOT NULL ,
`equipments_necklace` VARCHAR(75) NOT NULL ,
`equipments_finger_l` VARCHAR(75) NOT NULL ,
`equipments_finger_r` VARCHAR(75) NOT NULL ,
`equipments_ear_l` VARCHAR(75) NOT NULL ,
`equipments_ear_r` VARCHAR(75) NOT NULL ,
`hands_left` VARCHAR(75) NOT NULL , -- Note: sheet#q#sap
`hands_right` VARCHAR(75) NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER FACTION POINTS TABLE --
CREATE TABLE `character_faction_points_history` (
`cid` INT NOT NULL ,
`kami` INT NOT NULL ,
`karavan` INT NOT NULL ,
`fyros` INT NOT NULL ,
`matis` INT NOT NULL ,
`tryker` INT NOT NULL ,
`zorai` INT NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER FAMES TABLE --
CREATE TABLE `character_fames_history` (
`cid` INT NOT NULL ,
`fyros` INT NULL ,
`matis` INT NULL ,
`tryker` INT NULL ,
`zorai` INT NULL ,
`bandit` INT NULL ,
`civil` INT NULL ,
`degen` INT NULL ,
`fauna` INT NULL ,
`fauna_carnivore` INT NULL ,
`fauna_herbivore` INT NULL ,
`flora` INT NULL ,
`goo` INT NULL ,
`kami` INT NULL ,
`karavan` INT NULL ,
`kitin` INT NULL ,
`tribe_ancient_dryads` INT NULL ,
`tribe_antikamis` INT NULL ,
`tribe_barkers` INT NULL ,
`tribe_beachcombers` INT NULL ,
`tribe_black_circle` INT NULL ,
`tribe_cholorogoos` INT NULL ,
`tribe_cockroaches` INT NULL ,
`tribe_company_of_the_eternal_tree` INT NULL ,
`tribe_corsair` INT NULL ,
`tribe_cute` INT NULL ,
`tribe_darkening_sap` INT NULL ,
`tribe_dune_riders` INT NULL ,
`tribe_ecowarriors` INT NULL ,
`tribe_firebrands` INT NULL ,
`tribe_first_deserter` INT NULL ,
`tribe_frahar` INT NULL ,
`tribe_frahar_hunters` INT NULL ,
`tribe_gibbay` INT NULL ,
`tribe_goo_heads` INT NULL ,
`tribe_green_seed` INT NULL ,
`tribe_hamazans_of_the_dead_seed` INT NULL ,
`tribe_icon_workshipers` INT NULL ,
`tribe_keepers` INT NULL ,
`tribe_kitin_gatheres` INT NULL ,
`tribe_lagoon_brothers` INT NULL ,
`tribe_lawless` INT NULL ,
`tribe_leviers` INT NULL ,
`tribe_master_of_the_goo` INT NULL ,
`tribe_matisian_border_guards` INT NULL ,
`tribe_night_turners` INT NULL ,
`tribe_oasis_diggers` INT NULL ,
`tribe_pyromancers` INT NULL ,
`tribe_recoverers` INT NULL ,
`tribe_renegades` INT NULL ,
`tribe_restorers` INT NULL ,
`tribe_root_tappers` INT NULL ,
`tribe_sacred_sap` INT NULL ,
`tribe_sap_gleaners` INT NULL ,
`tribe_sap_slaves` INT NULL ,
`tribe_scorchers` INT NULL ,
`tribe_shadow_runners` INT NULL ,
`tribe_siblings_of_the_weeds` INT NULL ,
`tribe_silt_sculptors` INT NULL ,
`tribe_slavers` INT NULL ,
`tribe_smuglers` INT NULL ,
`tribe_the_arid_matis` INT NULL ,
`tribe_the_kuilde` INT NULL ,
`tribe_the_slash_and_burn` INT NULL ,
`tribe_tutors` INT NULL ,
`tribe_water_breakers` INT NULL ,
`tribe_woven_bridles` INT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER PETS TABLE --
CREATE TABLE `character_pets_history` (
`cid` INT NOT NULL ,
`pet0_sheet` VARCHAR(75) NOT NULL ,
`pet0_price` DOUBLE NOT NULL ,
`pet0_satiety` INT NOT NULL ,
`pet0_status` VARCHAR(50) NOT NULL ,
`pet0_stable` VARCHAR(50) NOT NULL ,
`pet0_position_x` DOUBLE NOT NULL ,
`pet0_position_y` DOUBLE NOT NULL ,
`pet1_sheet` VARCHAR(75) NOT NULL ,
`pet1_price` DOUBLE NOT NULL ,
`pet1_satiety` INT NOT NULL ,
`pet1_status` VARCHAR(50) NOT NULL ,
`pet1_stable` VARCHAR(50) NOT NULL ,
`pet1_position_x` DOUBLE NOT NULL ,
`pet1_position_y` DOUBLE NOT NULL ,
`pet2_sheet` VARCHAR(75) NOT NULL ,
`pet2_price` DOUBLE NOT NULL ,
`pet2_satiety` INT NOT NULL ,
`pet2_status` VARCHAR(50) NOT NULL ,
`pet2_stable` VARCHAR(50) NOT NULL ,
`pet2_position_x` DOUBLE NOT NULL ,
`pet2_position_y` DOUBLE NOT NULL ,
`pet3_sheet` VARCHAR(75) NOT NULL ,
`pet3_price` DOUBLE NOT NULL ,
`pet3_satiety` INT NOT NULL ,
`pet3_status` VARCHAR(50) NOT NULL ,
`pet3_stable` VARCHAR(50) NOT NULL ,
`pet3_position_x` DOUBLE NOT NULL ,
`pet3_position_y` DOUBLE NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER SKILLS TABLE --
CREATE TABLE `character_skills_history` (
`cid` INT NULL ,
`SH` INT NULL,
`SHF` INT NULL,
`SHFF` INT NULL,
`SHFFA` INT NULL,
`SHFFAE` INT NULL,
`SHFFAEM` INT NULL,
`SHFD` INT NULL,
`SHFDA` INT NULL,
`SHFDAE` INT NULL,
`SHFDAEM` INT NULL,
`SHFJ` INT NULL,
`SHFJA` INT NULL,
`SHFJAE` INT NULL,
`SHFJAEM` INT NULL,
`SHFL` INT NULL,
`SHFLA` INT NULL,
`SHFLAE` INT NULL,
`SHFLAEM` INT NULL,
`SHFP` INT NULL,
`SHFPA` INT NULL,
`SHFPAE` INT NULL,
`SHFPAEM` INT NULL,
`SM` INT NULL,
`SMD` INT NULL,
`SMDA` INT NULL,
`SMDAA` INT NULL,
`SMDAAE` INT NULL,
`SMDAAEM` INT NULL,
`SMDH` INT NULL,
`SMDHA` INT NULL,
`SMDHAE` INT NULL,
`SMDHAEM` INT NULL,
`SMO` INT NULL,
`SMOA` INT NULL,
`SMOAA` INT NULL,
`SMOAAE` INT NULL,
`SMOAAEM` INT NULL,
`SMOE` INT NULL,
`SMOEA` INT NULL,
`SMOEAE` INT NULL,
`SMOEAEM` INT NULL,
`SF` INT NULL,
`SFM` INT NULL,
`SFM1` INT NULL,
`SFM1B` INT NULL,
`SFM1BM` INT NULL,
`SFM1BMM` INT NULL,
`SFM1BS` INT NULL,
`SFM1BSM` INT NULL,
`SFM1P` INT NULL,
`SFM1PS` INT NULL,
`SFM1PSM` INT NULL,
`SFM1S` INT NULL,
`SFM1SA` INT NULL,
`SFM1SAM` INT NULL,
`SFM1SS` INT NULL,
`SFM1SSM` INT NULL,
`SFM2` INT NULL,
`SFM2B` INT NULL,
`SFM2BM` INT NULL,
`SFM2BMM` INT NULL,
`SFM2P` INT NULL,
`SFM2PP` INT NULL,
`SFM2PPM` INT NULL,
`SFM2S` INT NULL,
`SFM2SA` INT NULL,
`SFM2SAM` INT NULL,
`SFM2SS` INT NULL,
`SFM2SSM` INT NULL,
`SFMC` INT NULL,
`SFMCA` INT NULL,
`SFMCAD` INT NULL,
`SFMCADM` INT NULL,
`SFMCAH` INT NULL,
`SFMCAHM` INT NULL,
`SFR` INT NULL,
`SFR1` INT NULL,
`SFR1A` INT NULL,
`SFR1AB` INT NULL,
`SFR1ABM` INT NULL,
`SFR1AP` INT NULL,
`SFR1APM` INT NULL,
`SFR2` INT NULL,
`SFR2A` INT NULL,
`SFR2AA` INT NULL,
`SFR2AAM` INT NULL,
`SFR2AB` INT NULL,
`SFR2ABM` INT NULL,
`SFR2AL` INT NULL,
`SFR2ALM` INT NULL,
`SFR2AR` INT NULL,
`SFR2ARM` INT NULL,
`SC` INT NULL,
`SCA` INT NULL,
`SCJ` INT NULL,
`SCM` INT NULL,
`SCR` INT NULL,
`SCAH` INT NULL,
`SCAL` INT NULL,
`SCAM` INT NULL,
`SCAS` INT NULL,
`SCJA` INT NULL,
`SCJB` INT NULL,
`SCJD` INT NULL,
`SCJE` INT NULL,
`SCJP` INT NULL,
`SCJR` INT NULL,
`SCM1` INT NULL,
`SCM2` INT NULL,
`SCMC` INT NULL,
`SCR1` INT NULL,
`SCR2` INT NULL,
`SCAHB` INT NULL,
`SCAHG` INT NULL,
`SCAHH` INT NULL,
`SCAHP` INT NULL,
`SCAHS` INT NULL,
`SCAHV` INT NULL,
`SCALB` INT NULL,
`SCALG` INT NULL,
`SCALP` INT NULL,
`SCALS` INT NULL,
`SCALV` INT NULL,
`SCAMB` INT NULL,
`SCAMG` INT NULL,
`SCAMP` INT NULL,
`SCAMS` INT NULL,
`SCAMV` INT NULL,
`SCASS` INT NULL,
`SCASB` INT NULL,
`SCJAA` INT NULL,
`SCJBA` INT NULL,
`SCJDA` INT NULL,
`SCJEA` INT NULL,
`SCJPA` INT NULL,
`SCJRA` INT NULL,
`SCM1M` INT NULL,
`SCM1T` INT NULL,
`SCM1P` INT NULL,
`SCM1A` INT NULL,
`SCM1S` INT NULL,
`SCM1D` INT NULL,
`SCM2M` INT NULL,
`SCM2P` INT NULL,
`SCM2A` INT NULL,
`SCM2S` INT NULL,
`SCMCA` INT NULL,
`SCR1B` INT NULL,
`SCR1P` INT NULL,
`SCR2A` INT NULL,
`SCR2B` INT NULL,
`SCR2L` INT NULL,
`SCR2R` INT NULL,
`SCAHBE` INT NULL,
`SCAHGE` INT NULL,
`SCAHHE` INT NULL,
`SCAHPE` INT NULL,
`SCAHSE` INT NULL,
`SCAHVE` INT NULL,
`SCALBE` INT NULL,
`SCALGE` INT NULL,
`SCALPE` INT NULL,
`SCALSE` INT NULL,
`SCALVE` INT NULL,
`SCAMBE` INT NULL,
`SCAMGE` INT NULL,
`SCAMPE` INT NULL,
`SCAMSE` INT NULL,
`SCAMVE` INT NULL,
`SCASSE` INT NULL,
`SCASBE` INT NULL,
`SCJAAE` INT NULL,
`SCJBAE` INT NULL,
`SCJDAE` INT NULL,
`SCJEAE` INT NULL,
`SCJPAE` INT NULL,
`SCJRAE` INT NULL,
`SCM1ME` INT NULL,
`SCM1TE` INT NULL,
`SCM1PE` INT NULL,
`SCM1AE` INT NULL,
`SCM1SE` INT NULL,
`SCM1DE` INT NULL,
`SCM2ME` INT NULL,
`SCM2PE` INT NULL,
`SCM2AE` INT NULL,
`SCM2SE` INT NULL,
`SCMCAE` INT NULL,
`SCR1BE` INT NULL,
`SCR1PE` INT NULL,
`SCR2AE` INT NULL,
`SCR2BE` INT NULL,
`SCR2LE` INT NULL,
`SCR2RE` INT NULL,
`SCAHBEM` INT NULL,
`SCAHGEM` INT NULL,
`SCAHHEM` INT NULL,
`SCAHPEM` INT NULL,
`SCAHSEM` INT NULL,
`SCAHVEM` INT NULL,
`SCALBEM` INT NULL,
`SCALGEM` INT NULL,
`SCALPEM` INT NULL,
`SCALSEM` INT NULL,
`SCALVEM` INT NULL,
`SCAMBEM` INT NULL,
`SCAMGEM` INT NULL,
`SCAMPEM` INT NULL,
`SCAMSEM` INT NULL,
`SCAMVEM` INT NULL,
`SCASSEM` INT NULL,
`SCASBEM` INT NULL,
`SCJAAEM` INT NULL,
`SCJBAEM` INT NULL,
`SCJDAEM` INT NULL,
`SCJEAEM` INT NULL,
`SCJPAEM` INT NULL,
`SCJRAEM` INT NULL,
`SCM1MEM` INT NULL,
`SCM1TEM` INT NULL,
`SCM1PEM` INT NULL,
`SCM1AEM` INT NULL,
`SCM1SEM` INT NULL,
`SCM1DEM` INT NULL,
`SCM2MEM` INT NULL,
`SCM2PEM` INT NULL,
`SCM2AEM` INT NULL,
`SCM2SEM` INT NULL,
`SCMCAEM` INT NULL,
`SCR1BEM` INT NULL,
`SCR1PEM` INT NULL,
`SCR2AEM` INT NULL,
`SCR2BEM` INT NULL,
`SCR2LEM` INT NULL,
`SCR2REM` INT NULL,
`date` DOUBLE NOT NULL 
);


---------------------------------------------------------------------------------------------------
--                                            GUILD TABLES                                                       --
---------------------------------------------------------------------------------------------------

