---------------------------------------------------------------------------------------------------
--                                       DATABASE CREATION                                              --
---------------------------------------------------------------------------------------------------

-- CREATE DATABASE --
CREATE DATABASE `ryzom_api` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

---------------------------------------------------------------------------------------------------
--                                         GUILDS LIST TABLE                                                --
---------------------------------------------------------------------------------------------------

-- CREATE GUILDS LIST TABLE --
CREATE TABLE `ryzom_api`.`guilds_list` (
`gid` INT NOT NULL ,
`shardid` VARCHAR( 3 ) NOT NULL ,
`name` VARCHAR(120) NOT NULL ,
`race` VARCHAR(10) NOT NULL ,
`icon` VARCHAR(50) NOT NULL ,
`creation_date` DOUBLE NOT NULL ,
`description` TEXT NOT NULL ,
`deleted` BOOLEAN NOT NULL ,
`deletion_date` DOUBLE NOT NULL ,
UNIQUE (
`gid`
)
);

---------------------------------------------------------------------------------------------------
--                                      CHARACTER TABLES                                                   --
---------------------------------------------------------------------------------------------------

-- CREATE SINGLE CHARACTER TABLE --
CREATE TABLE `ryzom_api`.`character_history` (
`cid` INT NOT NULL ,
`uid` INT NOT NULL ,
`slot` INT NOT NULL ,
`shard` VARCHAR(10) NOT NULL ,
`race` VARCHAR(10) NOT NULL ,
`gender` VARCHAR(1) NOT NULL ,
`apikey` VARCHAR( 30 ) NOT NULL ,
`date_first` DOUBLE NOT NULL ,
`date_double` DOUBLE NOT NULL ,
UNIQUE (
`cid`
)
);

-- CREATE SINGLE CHARACTER INFO TABLE --
CREATE TABLE `ryzom_api`.`character_info_history` (
`cid` INT NOT NULL ,
`name` VARCHAR(16) NOT NULL ,
`titleid` VARCHAR(75) NOT NULL ,
`played_time` DOUBLE NOT NULL ,
`money` DOUBLE NOT NULL ,
`cult` VARCHAR(10) NOT NULL ,
`civ` VARCHAR(10) NOT NULL ,
`building` VARCHAR(15) NOT NULL ,
`guild_gid` VARCHAR(15) NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER PHYS CARACS TABLE --
CREATE TABLE `ryzom_api`.`character_phys_caracs_history` (
`cid` INT NOT NULL ,
`constitution` INT NOT NULL ,
`metabolism` INT NOT NULL ,
`intelligence` INT NOT NULL ,
`wisdom` INT NOT NULL ,
`strength` INT NOT NULL ,
`wellbalanced` INT NOT NULL ,
`dexterity` INT NOT NULL ,
`will` INT NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER PHYS SCORES TABLE --
CREATE TABLE `ryzom_api`.`character_phys_scores_history` (
`cid` INT NOT NULL ,
`hitpoints` INT NOT NULL ,
`hitpoints_max` INT NOT NULL ,
`stamina` INT NOT NULL ,
`stamina_max` INT NOT NULL ,
`sap` INT NOT NULL ,
`sap_max` INT NOT NULL ,
`focus` INT NOT NULL ,
`focus_max` INT NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER EQUIPHANDS TABLE --
CREATE TABLE `ryzom_api`.`character_equiphands_history` (
`cid` INT NOT NULL ,
`equipments_feet` VARCHAR(75) NOT NULL , -- Note: sheet#c#q (e.g. ictahb_3.sitem#0#250)
`equipments_hands` VARCHAR(75) NOT NULL ,
`equipments_legs` VARCHAR(75) NOT NULL ,
`equipments_arms` VARCHAR(75) NOT NULL ,
`equipments_chest` VARCHAR(75) NOT NULL ,
`equipments_ankle_l` VARCHAR(75) NOT NULL ,
`equipments_ankle_r` VARCHAR(75) NOT NULL ,
`equipments_wrist_l` VARCHAR(75) NOT NULL ,
`equipments_wrist_r` VARCHAR(75) NOT NULL ,
`equipments_head_dress` VARCHAR(75) NOT NULL ,
`equipments_necklace` VARCHAR(75) NOT NULL ,
`equipments_finger_l` VARCHAR(75) NOT NULL ,
`equipments_finger_r` VARCHAR(75) NOT NULL ,
`equipments_ear_l` VARCHAR(75) NOT NULL ,
`equipments_ear_r` VARCHAR(75) NOT NULL ,
`hands_left` VARCHAR(75) NOT NULL , -- Note: sheet#q#sap
`hands_right` VARCHAR(75) NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER FACTION POINTS TABLE --
CREATE TABLE `ryzom_api`.`character_faction_points_history` (
`cid` INT NOT NULL ,
`kami` INT NOT NULL ,
`karavan` INT NOT NULL ,
`fyros` INT NOT NULL ,
`matis` INT NOT NULL ,
`tryker` INT NOT NULL ,
`zorai` INT NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER FAMES TABLE --
CREATE TABLE `ryzom_api`.`character_fames_history` (
`cid` INT NOT NULL ,
`fyros` INT NOT NULL ,
`matis` INT NOT NULL ,
`tryker` INT NOT NULL ,
`zorai` INT NOT NULL ,
`bandit` INT NOT NULL ,
`civil` INT NOT NULL ,
`degen` INT NOT NULL ,
`fauna` INT NOT NULL ,
`fauna_carnivore` INT NOT NULL ,
`fauna_herbivore` INT NOT NULL ,
`flora` INT NOT NULL ,
`goo` INT NOT NULL ,
`kami` INT NOT NULL ,
`karavan` INT NOT NULL ,
`kitin` INT NOT NULL ,
`tribe_ancient_dryads` INT NOT NULL ,
`tribe_antikamis` INT NOT NULL ,
`tribe_barkers` INT NOT NULL ,
`tribe_beachcombers` INT NOT NULL ,
`tribe_black_circle` INT NOT NULL ,
`tribe_cholorogoos` INT NOT NULL ,
`tribe_cockroaches` INT NOT NULL ,
`tribe_company_of_the_eternal_tree` INT NOT NULL ,
`tribe_corsair` INT NOT NULL ,
`tribe_cute` INT NOT NULL ,
`tribe_darkening_sap` INT NOT NULL ,
`tribe_dune_riders` INT NOT NULL ,
`tribe_ecowarriors` INT NOT NULL ,
`tribe_firebrands` INT NOT NULL ,
`tribe_first_deserter` INT NOT NULL ,
`tribe_frahar` INT NOT NULL ,
`tribe_frahar_hunters` INT NOT NULL ,
`tribe_gibbay` INT NOT NULL ,
`tribe_goo_heads` INT NOT NULL ,
`tribe_green_seed` INT NOT NULL ,
`tribe_hamazans_of_the_dead_seed` INT NOT NULL ,
`tribe_icon_workshipers` INT NOT NULL ,
`tribe_keepers` INT NOT NULL ,
`tribe_kitin_gatheres` INT NOT NULL ,
`tribe_lagoon_brothers` INT NOT NULL ,
`tribe_lawless` INT NOT NULL ,
`tribe_leviers` INT NOT NULL ,
`tribe_master_of_the_goo` INT NOT NULL ,
`tribe_matisian_border_guards` INT NOT NULL ,
`tribe_night_turners` INT NOT NULL ,
`tribe_oasis_diggers` INT NOT NULL ,
`tribe_pyromancers` INT NOT NULL ,
`tribe_recoverers` INT NOT NULL ,
`tribe_renegades` INT NOT NULL ,
`tribe_restorers` INT NOT NULL ,
`tribe_root_tappers` INT NOT NULL ,
`tribe_sacred_sap` INT NOT NULL ,
`tribe_sap_gleaners` INT NOT NULL ,
`tribe_sap_slaves` INT NOT NULL ,
`tribe_scorchers` INT NOT NULL ,
`tribe_shadow_runners` INT NOT NULL ,
`tribe_siblings_of_the_weeds` INT NOT NULL ,
`tribe_silt_sculptors` INT NOT NULL ,
`tribe_slavers` INT NOT NULL ,
`tribe_smuglers` INT NOT NULL ,
`tribe_the_arid_matis` INT NOT NULL ,
`tribe_the_kuilde` INT NOT NULL ,
`tribe_the_slash_and_burn` INT NOT NULL ,
`tribe_tutors` INT NOT NULL ,
`tribe_water_breakers` INT NOT NULL ,
`tribe_woven_bridles` INT NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER PETS TABLE --
CREATE TABLE `ryzom_api`.`character_pets_history` (
`cid` INT NOT NULL ,
`pet0_sheet` VARCHAR(75) NOT NULL ,
`pet0_price` DOUBLE NOT NULL ,
`pet0_satiety` INT NOT NULL ,
`pet0_status` VARCHAR(50) NOT NULL ,
`pet0_stable` VARCHAR(50) NOT NULL ,
`pet0_position_x` DOUBLE NOT NULL ,
`pet0_position_y` DOUBLE NOT NULL ,
`pet1_sheet` VARCHAR(75) NOT NULL ,
`pet1_price` DOUBLE NOT NULL ,
`pet1_satiety` INT NOT NULL ,
`pet1_status` VARCHAR(50) NOT NULL ,
`pet1_stable` VARCHAR(50) NOT NULL ,
`pet1_position_x` DOUBLE NOT NULL ,
`pet1_position_y` DOUBLE NOT NULL ,
`pet2_sheet` VARCHAR(75) NOT NULL ,
`pet2_price` DOUBLE NOT NULL ,
`pet2_satiety` INT NOT NULL ,
`pet2_status` VARCHAR(50) NOT NULL ,
`pet2_stable` VARCHAR(50) NOT NULL ,
`pet2_position_x` DOUBLE NOT NULL ,
`pet2_position_y` DOUBLE NOT NULL ,
`pet3_sheet` VARCHAR(75) NOT NULL ,
`pet3_price` DOUBLE NOT NULL ,
`pet3_satiety` INT NOT NULL ,
`pet3_status` VARCHAR(50) NOT NULL ,
`pet3_stable` VARCHAR(50) NOT NULL ,
`pet3_position_x` DOUBLE NOT NULL ,
`pet3_position_y` DOUBLE NOT NULL ,
`date` DOUBLE NOT NULL 
);

-- CREATE SINGLE CHARACTER SKILLS TABLE --
CREATE TABLE `ryzom_api`.`character_skills_history` (
`cid` INT NOT NULL ,
`SH` INT NOT NULL,
`SHF` INT NOT NULL,
`SHFF` INT NOT NULL,
`SHFFA` INT NOT NULL,
`SHFFAE` INT NOT NULL,
`SHFFAEM` INT NOT NULL,
`SHFD` INT NOT NULL,
`SHFDA` INT NOT NULL,
`SHFDAE` INT NOT NULL,
`SHFDAEM` INT NOT NULL,
`SHFJ` INT NOT NULL,
`SHFJA` INT NOT NULL,
`SHFJAE` INT NOT NULL,
`SHFJAEM` INT NOT NULL,
`SHFL` INT NOT NULL,
`SHFLA` INT NOT NULL,
`SHFLAE` INT NOT NULL,
`SHFLAEM` INT NOT NULL,
`SHFP` INT NOT NULL,
`SHFPA` INT NOT NULL,
`SHFPAE` INT NOT NULL,
`SHFPAEM` INT NOT NULL,
`SM` INT NOT NULL,
`SMD` INT NOT NULL,
`SMDA` INT NOT NULL,
`SMDAA` INT NOT NULL,
`SMDAAE` INT NOT NULL,
`SMDAAEM` INT NOT NULL,
`SMDH` INT NOT NULL,
`SMDHA` INT NOT NULL,
`SMDHAE` INT NOT NULL,
`SMDHAEM` INT NOT NULL,
`SMO` INT NOT NULL,
`SMOA` INT NOT NULL,
`SMOAA` INT NOT NULL,
`SMOAAE` INT NOT NULL,
`SMOAAEM` INT NOT NULL,
`SMOE` INT NOT NULL,
`SMOEA` INT NOT NULL,
`SMOEAE` INT NOT NULL,
`SMOEAEM` INT NOT NULL,
`SF` INT NOT NULL,
`SFM` INT NOT NULL,
`SFM1` INT NOT NULL,
`SFM1B` INT NOT NULL,
`SFM1BM` INT NOT NULL,
`SFM1BMM` INT NOT NULL,
`SFM1BS` INT NOT NULL,
`SFM1BSM` INT NOT NULL,
`SFM1P` INT NOT NULL,
`SFM1PS` INT NOT NULL,
`SFM1PSM` INT NOT NULL,
`SFM1S` INT NOT NULL,
`SFM1SA` INT NOT NULL,
`SFM1SAM` INT NOT NULL,
`SFM1SS` INT NOT NULL,
`SFM1SSM` INT NOT NULL,
`SFM2` INT NOT NULL,
`SFM2B` INT NOT NULL,
`SFM2BM` INT NOT NULL,
`SFM2BMM` INT NOT NULL,
`SFM2P` INT NOT NULL,
`SFM2PP` INT NOT NULL,
`SFM2PPM` INT NOT NULL,
`SFM2S` INT NOT NULL,
`SFM2SA` INT NOT NULL,
`SFM2SAM` INT NOT NULL,
`SFM2SS` INT NOT NULL,
`SFM2SSM` INT NOT NULL,
`SFMC` INT NOT NULL,
`SFMCA` INT NOT NULL,
`SFMCAD` INT NOT NULL,
`SFMCADM` INT NOT NULL,
`SFMCAH` INT NOT NULL,
`SFMCAHM` INT NOT NULL,
`SFR` INT NOT NULL,
`SFR1` INT NOT NULL,
`SFR1A` INT NOT NULL,
`SFR1AB` INT NOT NULL,
`SFR1ABM` INT NOT NULL,
`SFR1AP` INT NOT NULL,
`SFR1APM` INT NOT NULL,
`SFR2` INT NOT NULL,
`SFR2A` INT NOT NULL,
`SFR2AA` INT NOT NULL,
`SFR2AAM` INT NOT NULL,
`SFR2AB` INT NOT NULL,
`SFR2ABM` INT NOT NULL,
`SFR2AL` INT NOT NULL,
`SFR2ALM` INT NOT NULL,
`SFR2AR` INT NOT NULL,
`SFR2ARM` INT NOT NULL,
`SC` INT NOT NULL,
`SCA` INT NOT NULL,
`SCJ` INT NOT NULL,
`SCM` INT NOT NULL,
`SCR` INT NOT NULL,
`SCAH` INT NOT NULL,
`SCAL` INT NOT NULL,
`SCAM` INT NOT NULL,
`SCAS` INT NOT NULL,
`SCJA` INT NOT NULL,
`SCJB` INT NOT NULL,
`SCJD` INT NOT NULL,
`SCJE` INT NOT NULL,
`SCJP` INT NOT NULL,
`SCJR` INT NOT NULL,
`SCM1` INT NOT NULL,
`SCM2` INT NOT NULL,
`SCMC` INT NOT NULL,
`SCR1` INT NOT NULL,
`SCR2` INT NOT NULL,
`SCAHB` INT NOT NULL,
`SCAHG` INT NOT NULL,
`SCAHH` INT NOT NULL,
`SCAHP` INT NOT NULL,
`SCAHS` INT NOT NULL,
`SCAHV` INT NOT NULL,
`SCALB` INT NOT NULL,
`SCALG` INT NOT NULL,
`SCALP` INT NOT NULL,
`SCALS` INT NOT NULL,
`SCALV` INT NOT NULL,
`SCAMB` INT NOT NULL,
`SCAMG` INT NOT NULL,
`SCAMP` INT NOT NULL,
`SCAMS` INT NOT NULL,
`SCAMV` INT NOT NULL,
`SCASS` INT NOT NULL,
`SCASB` INT NOT NULL,
`SCJAA` INT NOT NULL,
`SCJBA` INT NOT NULL,
`SCJDA` INT NOT NULL,
`SCJEA` INT NOT NULL,
`SCJPA` INT NOT NULL,
`SCJRA` INT NOT NULL,
`SCM1M` INT NOT NULL,
`SCM1T` INT NOT NULL,
`SCM1P` INT NOT NULL,
`SCM1A` INT NOT NULL,
`SCM1S` INT NOT NULL,
`SCM1D` INT NOT NULL,
`SCM2M` INT NOT NULL,
`SCM2P` INT NOT NULL,
`SCM2A` INT NOT NULL,
`SCM2S` INT NOT NULL,
`SCMCA` INT NOT NULL,
`SCR1B` INT NOT NULL,
`SCR1P` INT NOT NULL,
`SCR2A` INT NOT NULL,
`SCR2B` INT NOT NULL,
`SCR2L` INT NOT NULL,
`SCR2R` INT NOT NULL,
`SCAHBE` INT NOT NULL,
`SCAHGE` INT NOT NULL,
`SCAHHE` INT NOT NULL,
`SCAHPE` INT NOT NULL,
`SCAHSE` INT NOT NULL,
`SCAHVE` INT NOT NULL,
`SCALBE` INT NOT NULL,
`SCALGE` INT NOT NULL,
`SCALPE` INT NOT NULL,
`SCALSE` INT NOT NULL,
`SCALVE` INT NOT NULL,
`SCAMBE` INT NOT NULL,
`SCAMGE` INT NOT NULL,
`SCAMPE` INT NOT NULL,
`SCAMSE` INT NOT NULL,
`SCAMVE` INT NOT NULL,
`SCASSE` INT NOT NULL,
`SCASBE` INT NOT NULL,
`SCJAAE` INT NOT NULL,
`SCJBAE` INT NOT NULL,
`SCJDAE` INT NOT NULL,
`SCJEAE` INT NOT NULL,
`SCJPAE` INT NOT NULL,
`SCJRAE` INT NOT NULL,
`SCM1ME` INT NOT NULL,
`SCM1TE` INT NOT NULL,
`SCM1PE` INT NOT NULL,
`SCM1AE` INT NOT NULL,
`SCM1SE` INT NOT NULL,
`SCM1DE` INT NOT NULL,
`SCM2ME` INT NOT NULL,
`SCM2PE` INT NOT NULL,
`SCM2AE` INT NOT NULL,
`SCM2SE` INT NOT NULL,
`SCMCAE` INT NOT NULL,
`SCR1BE` INT NOT NULL,
`SCR1PE` INT NOT NULL,
`SCR2AE` INT NOT NULL,
`SCR2BE` INT NOT NULL,
`SCR2LE` INT NOT NULL,
`SCR2RE` INT NOT NULL,
`SCAHBEM` INT NOT NULL,
`SCAHGEM` INT NOT NULL,
`SCAHHEM` INT NOT NULL,
`SCAHPEM` INT NOT NULL,
`SCAHSEM` INT NOT NULL,
`SCAHVEM` INT NOT NULL,
`SCALBEM` INT NOT NULL,
`SCALGEM` INT NOT NULL,
`SCALPEM` INT NOT NULL,
`SCALSEM` INT NOT NULL,
`SCALVEM` INT NOT NULL,
`SCAMBEM` INT NOT NULL,
`SCAMGEM` INT NOT NULL,
`SCAMPEM` INT NOT NULL,
`SCAMSEM` INT NOT NULL,
`SCAMVEM` INT NOT NULL,
`SCASSEM` INT NOT NULL,
`SCASBEM` INT NOT NULL,
`SCJAAEM` INT NOT NULL,
`SCJBAEM` INT NOT NULL,
`SCJDAEM` INT NOT NULL,
`SCJEAEM` INT NOT NULL,
`SCJPAEM` INT NOT NULL,
`SCJRAEM` INT NOT NULL,
`SCM1MEM` INT NOT NULL,
`SCM1TEM` INT NOT NULL,
`SCM1PEM` INT NOT NULL,
`SCM1AEM` INT NOT NULL,
`SCM1SEM` INT NOT NULL,
`SCM1DEM` INT NOT NULL,
`SCM2MEM` INT NOT NULL,
`SCM2PEM` INT NOT NULL,
`SCM2AEM` INT NOT NULL,
`SCM2SEM` INT NOT NULL,
`SCMCAEM` INT NOT NULL,
`SCR1BEM` INT NOT NULL,
`SCR1PEM` INT NOT NULL,
`SCR2AEM` INT NOT NULL,
`SCR2BEM` INT NOT NULL,
`SCR2LEM` INT NOT NULL,
`SCR2REM` INT NOT NULL,
`date` DOUBLE NOT NULL 
);


---------------------------------------------------------------------------------------------------
--                                            GUILD TABLES                                                       --
---------------------------------------------------------------------------------------------------

